// <auto-generated />
namespace WebAppAngular5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FeeDetails_PaidDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeeDetails_PaidDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131026550_FeeDetails_PaidDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
